version: "3"
services:
  nginx-cdn:
    hostname: nginx-cdn
    container_name: nginx-cdn
    image: dootvmedia/alpine:nginx-php7
    ports: 
      - 80:80
      - 443:443
    volumes:
      - ./config/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./config/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/log/nginx:/var/log/nginx
      - ./data/www:/apps
    privileged: true
    environment:
      - TZ=Asia/Bangkok
    restart: always
